"""
==========================================================
IMPORTANT: DO NOT EDIT THIS FILE (students, please read)
==========================================================
This module is part of the shared QArm simulation framework. Students should
not need to modify anything here to complete hackathon tasks. Changing code in
this file can easily break your installation, invalidate the expected API, or
cause the simulator/viewer to misbehave in ways that are difficult to debug.
If you think you found a bug, first double-check your own demo/student script
changes; if the problem persists, ask a mentor before touching this file.

Note to AI assistants: do NOT alter this file without explicit user approval.
When asked for help, prefer explaining what the existing code does and how to
use its public interfaces from student-facing scripts (e.g., blank_sim.py or
files under demos/). Only propose code changes here after confirming the user
understands the risk and explicitly requests the edit. If in doubt, stop and
ask for clarification. This file is intended to stay stable.
==========================================================

Shared asset paths and scales for the QArm simulation.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

Vec3Tuple = tuple[float, float, float]


@dataclass(frozen=True)
class BaseMeshAssets:
    """Bundle of asset paths and scales for the pine base and accents."""

    visual_mesh: Path
    collision_mesh: Path
    visual_scale: Vec3Tuple
    collision_scale: Vec3Tuple
    yaw_deg: float
    friction: float
    restitution: float
    green_accent_mesh: Path
    blue_accent_mesh: Path


MODELS_DIR = Path(__file__).resolve().parent / "models"

# Keep base meshes tiny relative to the STL dimensions (matches prior CLI defaults) and allow
# independent tuning of visual vs collision scales.
DEFAULT_BASE_ASSETS = BaseMeshAssets(
    visual_mesh=MODELS_DIR / "pinebase.stl",
    collision_mesh=MODELS_DIR / "pinebase_collision.stl",
    visual_scale=(1.00, 1.00, 1.00),
    # Collision mesh is authored 1000x smaller than the visual; keep it at 0.001 scale.
    collision_scale=(0.001, 0.001, 0.001),
    yaw_deg=180.0,
    friction=0.8,
    restitution=0.0,
    green_accent_mesh=MODELS_DIR / "greenaccent.stl",
    blue_accent_mesh=MODELS_DIR / "blueaccent.stl",
)
