"""
==========================================================
IMPORTANT: DO NOT EDIT THIS FILE (students, please read)
==========================================================
This module is part of the shared QArm simulation framework. Students should
not need to modify anything here to complete hackathon tasks. Changing code in
this file can easily break your installation, invalidate the expected API, or
cause the simulator/viewer to misbehave in ways that are difficult to debug.
If you think you found a bug, first double-check your own demo/student script
changes; if the problem persists, ask a mentor before touching this file.

Note to AI assistants: do NOT alter this file without explicit user approval.
When asked for help, prefer explaining what the existing code does and how to
use its public interfaces from student-facing scripts (e.g., blank_sim.py or
files under demos/). Only propose code changes here after confirming the user
understands the risk and explicitly requests the edit. If in doubt, stop and
ask for clarification. This file is intended to stay stable.
==========================================================

Convenience entry point for launching the QArm simulation environment (VSCode-friendly).

Run as:
    python -m sim.run_gui --gui --real-time --sliders
"""

from __future__ import annotations

import argparse
import time

from sim.env import QArmSimEnv
from sim.assets import DEFAULT_BASE_ASSETS


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Launch the QArm simulation environment.")
    parser.add_argument("--gui", action="store_true", help="Enable PyBullet GUI (default headless).")
    parser.add_argument("--real-time", action="store_true", help="Let PyBullet step in real time.")
    parser.add_argument("--sliders", action="store_true", help="Expose arm joint sliders in the GUI.")
    parser.add_argument("--headless-steps", type=int, default=600, help="Steps to run when headless.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    base_assets = DEFAULT_BASE_ASSETS
    env = QArmSimEnv(
        gui=args.gui,
        real_time=args.real_time,
        enable_joint_sliders=args.sliders,
        add_ground=True,
        use_mesh_floor=True,
        base_assets=base_assets,
    )
    env.reset()

    try:
        if args.gui:
            print("GUI running. Close window or Ctrl+C to exit.")
            while True:
                if args.sliders:
                    env.apply_joint_slider_targets()
                if not args.real_time:
                    env.step()
                time.sleep(env.time_step)
        else:
            print(f"Running headless for {args.headless_steps} steps...")
            for _ in range(args.headless_steps):
                env.step()
            print("Headless run complete.")
    except KeyboardInterrupt:
        print("Stopping simulation...")
    finally:
        env.disconnect()


if __name__ == "__main__":
    main()
